# Here we store all settings, credentials and constants.

#Pycom import for LoRa constants.
from network import LoRa

# LoRa config info.
LORA_MODE = LoRa.LORAWAN
LORA_REGION = LoRa.EU868
LORA_ACTIVATION = LoRa.OTAA
APP_EUI = '30AEA459134C0000'
APP_KEY = '38C9AD4E8B69241FE50AB179932CAE1F'
MEASURE_INTERVAL = 360
DISPLAY_TIME = 5
WAKE_TIME = 2
SLEEP_TIME = max(5, MEASURE_INTERVAL - 3*DISPLAY_TIME - WAKE_TIME)
SDS011_WAKE_TIME = 30 - WAKE_TIME
DEBUG_MODE = True
